### ISSUE TITLE
IE 10 and 11 has issues with nextTick - "invalid calling object"

### ISSUE THREAD

**Issue by abritinthebay** [reflux/refluxjs#374] opened 2015-07-21 23:48 UTC
When calling triggerAsync IE10+ throws this error. 

It's a simple problem. IE, because it's goddamn stupid, [rewrites this line of code](https://github.com/spoike/refluxjs/blob/master/src/utils.js#L38) to use setImmediate rather than `setTimeout(fn, 0)`. 

Which doesn't sound too bad, right? Well it wouldn't be except IE10+ treats it as if it has no call context now, causing this error.

The simple fix is to have something like this somewhere in the code:

```
window.setImmediate = window.setImmediate.bind(window); // because IE IS STUPID.
```

but quite how you'd want to handle this in this library is up to you. The above works for me but I have a feeling this is not an ideal solution for a library.

**Comment by LongLiveCHIEF** [comment] 2015-07-22 23:56
we're moving to the observable pattern with the 0.3 branch, which should clean up a lot of the `setTimeout`'s lounging around.

**Comment by spoike** [comment] 2015-07-23 03:23
I'll add the fix to the 0.2 branch since IE is a major browser vendor, stupid or not.

**Comment by abritinthebay** [comment] 2015-07-23 07:10
Hmmm in my case I found that just replacing with setImmediate didn't work without the bind... annoyingly. You need to bind the context before using it - else you get the invalid calling object error (least useful error message ever).

Basically due to the closure (or.. something) IE thinks you're passing a reference pointer around and disallows it... for reasons. The bind fixes that calling context.

**Comment by spoike** [comment] 2015-07-23 11:24
@abritinthebay I released a hotfix in v0.2.11, and `nextTick` uses `setImmediate` if it is available instead of `setTimeout`. Should sort out the issue, let me know if it didn't work (since I don't have Windows installed with IE10 on my mac laptop and I haven't gotten saucelabs test to work yet to verify).

**Comment by LongLiveCHIEF** [comment] 2015-07-23 23:46
IE. Must. Die.

**Comment by spoike** [comment] 2015-08-11 06:45
This should've been fixed in 0.2.11 and the browser tests work.

**Comment by emmkong** [comment] 2015-08-11 07:56
Hi Spoike,

The setImmediate cause issue with ES6 polyfill.
 If we include babel polyfill / core-js polyfill before reflux the setImmediate doesn't work. (p.s. We use browserify and babel)

**Comment by airmanx86** [comment] 2015-08-11 08:26
The original call context issue has nothing to do with replacing setTimeout with setImmediate anyway. Rather than using an experimental ES7 or IE / NodeJS only feature, changing it back to setTimeout and properly reproduce the original issue and fix it is the better approach. Besides setImmediate `method is not expected to become standard, and is only implemented by recent builds of Internet Explorer and Node.js 0.10+. It meets resistance both from Gecko (Firefox) and Webkit (Google/Apple).` https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate

**Comment by abritinthebay** [comment] 2015-08-11 19:26
Yes but read the actual bug:

> It's a simple problem. IE, because it's goddamn stupid, rewrites this line of code to use setImmediate rather than setTimeout(fn, 0).

If it does that then no amount of handwringing over the actual standard will fix it and IE will be busted.

**Comment by spoike** [comment] 2015-08-12 04:21
I guess I need to investigate it further with the web tests since I haven't been able to repro it yet.

**Comment by airmanx86** [comment] 2015-08-13 04:44
More precisely, the issue is to do with babel core-js polyfill which make `setImmediate` available for reflux to use. But browserify generated code would fail during unit testing with karma / jasmine / phantomjs combo. When overriding `nextTick` with `setTimeout`, the problem disappear. I have not investigate enough for this one, may be the calling context for `setTimeout` and `setImmediate` are different by default (but i am just speculating).

**Comment by spoike** [comment] 2015-10-13 03:59
I've removed the `setImmediate` implementation to avoid the babel SNAFU. If you want to use that or a polyfill, you have to set it yourself in `Reflux.nextTick`.

**Closed by spoike** 2015-10-13 03:59 UTC
Labels: bug

**Comment by airmanx86** [comment] 2015-11-06 00:06
That sounds great @spoike thanks :)

**Comment by RomanBartson** [comment] 2018-02-05 10:14
I replaced setTimeout(fn, 0)
to window.setTimeout(fn.bind(window),0) and it helped me.
