### ISSUE TITLE
Uncaught Error: Invariant Violation: replaceState(...): Can only update a mounted or mounting component.

### ISSUE THREAD

**Issue by jimbolla** [reflux/refluxjs#276] opened 2015-03-03 01:37 UTC
It appears Reflux.connect(...) doesn't check for this.isMounted() before calling this.setState(). This can cause the above error in the case where a parent and child component are listening to the same store, and the parent component includes/excludes the child based on that state:

    var action =  Reflux.createAction({ asyncResult: true, children: ['started'] });

    action.listen() {

        action.started();
        $.post(...)
            .done(action.completed)
            .fail(action.failed);
    });

    var store = Reflux.createStore({
        listenables: [action],

        state: {
            data: [],
            total: 0,
            searchInProgress: false,
        },

        getInitialState() {
            return this.state;
        },

        setState(...newState) {
            this.state = _.assign({}, this.state, ...newState);
            this.trigger(this.state);
        },

        searchStarted() {
            this.setState({ searchInProgress: true });
        },

        searchCompleted(response) {
            this.setState({ searchInProgress: false }, response);
        }
    });

    var Results = React.createClass({
        mixins: [Reflux.connect(store)],
        // ...
    });

    var Screen = React.createClass({
        mixins: [Reflux.connect(store)],

        render() {

            return <span>
                // ...

                { this.state.searchInProgress
                    ? <Spinner />
                    : <Results />}
            </span>
        }
    });

**Comment by mikhuang** [comment] 2015-03-10 16:26
This may be a duplicate of https://github.com/spoike/refluxjs/issues/246. I attempted to address this in https://github.com/spoike/refluxjs/pull/239 (but it's more of a hack than a true fix)

**Comment by devinivy** [comment] 2016-01-30 17:17
#239 was merged and released some time back.  We're now revisiting the issue in #393, as `isMounted()` is deprecated.

**Closed by devinivy** 2016-01-30 17:17 UTC
Labels: bug
