### ISSUE TITLE
Create TypeScript definitions

### ISSUE THREAD

**Issue by szahn** [reflux/refluxjs#443] opened 2016-01-07 21:40 UTC
Couldn't find the reflux type definitions in http://definitelytyped.org/tsd/. Would be helpful to have tsd's for those of us who write React in Typescript.

**Comment by szahn** [comment] 2016-01-07 23:36
A TypeScript guide would also be helpful.

**Comment by devinivy** [comment] 2016-01-31 15:39
Closing as dupe of #413 .  This would be nice, but I think we'd request help from the community, given that there aren't any maintainers that use TypeScript.

**Closed by devinivy** 2016-01-31 15:39 UTC
