### ISSUE TITLE
Please add "dist" folder to npm package.

### ISSUE THREAD

**Issue by neformal13** [reflux/refluxjs#441] opened 2015-12-07 14:30 UTC

**Comment by devinivy** [comment] 2016-01-30 06:00
Hi @neformal13– this seems to be a dupe of an old issue.  More info at https://github.com/reflux/refluxjs/issues/397.  If #448 is reconsidered, I'll try to update you here.

**Comment by jmcriffey** [comment] 2016-01-30 07:38
@neformal13 in the meantime, I created a package called reflux-dist in npm that is just a mirror of this package without the issue.

**Comment by devinivy** [comment] 2016-01-30 15:27
Good to know for others who run into this issue– thanks @jmcriffey.

@jmcriffey and @neformal13 can you explain your workflow and why it doesn't use a webpack/browserify to bundle the commonjs modules you use?  Could you point to other libraries that ship a `dist` on npm?

**Comment by jmcriffey** [comment] 2016-01-30 16:20
Basically none of the other modules I can think of need to go through my build; they all include a dist in an npm repo. Having to build this package is disruptive to a workflow that seems pretty common. By not distributing a build, you are also expecting me to compile the same way as this package. Imagine my build process used a very small subset of ES2015 or only targeted JSX, then I'd be in trouble trying to compile reflux-core.

To name a few libraries that include a dist in the npm repo: React, Lodash, D3,  Babel's Polyfill, Moment, Redux.

**Comment by devinivy** [comment] 2016-01-30 19:46
You make a good case!  I leave this up to @spoike to make the final call.

**Comment by devinivy** [comment] 2016-02-01 13:50
Closed by #448.  Thanks to both of you for bearing with us.

**Closed by devinivy** 2016-02-01 13:50 UTC

**Comment by jmcriffey** [comment] 2016-02-01 18:56
Thanks @devinivy, I appreciate it!

**Comment by devinivy** [comment] 2016-03-09 02:53
v0.3.1 is identical to v0.3.0, but includes the dist folder on npm.
